import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { toast } from 'react-toastify';
import { useGitHubAuth } from '../../../features/github/hooks/useGitHubAuth';
import { type DeploymentTarget } from '../../../features/github/hooks/useGitHubRepo';
import { useRenderDeploy } from '../../../features/deploy/hooks/useRenderDeploy';
import { LocalStorageRepository } from '../../../shared/services/storage/local-storage-repository';
import { ProjectStorageRepository } from '../../../shared/services/storage/ProjectStorageRepository';
import type { BesserProject } from '../../../shared/types/project';
import { getPostHog } from '../../../shared/services/analytics/lazy-analytics';
import {
  buildPersonalizationMapping,
  hasPersonalizationVariants,
  type PersonalizationMappingEntry,
} from '../../../features/deploy/utils/agentPersonalizationPayload';
import {
  restoreBaseAgentModels,
  stripAgentConfigToSystem,
} from '../../../features/deploy/utils/restoreBaseAgentModels';

const sanitizeRepoName = (name: string): string => {
  return name
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9-_]+/g, '-')
    .replace(/-{2,}/g, '-')
    .replace(/^-+|-+$/g, '');
};

const hasWebAppDeploymentInputs = (project: BesserProject | null): boolean => {
  if (!project) return false;
  const hasClassDiagram = project.diagrams.ClassDiagram.some((diagram) => Boolean(diagram?.model));
  const hasGuiDiagram = project.diagrams.GUINoCodeDiagram.some((diagram) => Boolean(diagram?.model));
  return hasClassDiagram && hasGuiDiagram;
};

const hasAgentDeploymentInputs = (project: BesserProject | null): boolean => {
  if (!project) return false;
  return project.diagrams.AgentDiagram.some((diagram) => {
    if (!diagram?.model || typeof diagram.model !== 'object') return false;
    const modelWithElements = diagram.model as { elements?: Record<string, unknown> };
    return Boolean(modelWithElements.elements && Object.keys(modelWithElements.elements).length > 0);
  });
};

const defaultRepoNameForTarget = (projectName: string, target: DeploymentTarget): string => {
  const baseName = sanitizeRepoName(projectName || '');
  if (target === 'agent') {
    if (!baseName) return 'besser-agent';
    return baseName.endsWith('-agent') ? baseName : `${baseName}-agent`;
  }
  return baseName || 'besser-webapp';
};

const defaultDescriptionForTarget = (target: DeploymentTarget): string => (
  target === 'agent'
    ? 'Standalone agent generated by BESSER'
    : 'Web application generated by BESSER'
);

// Picks the deployment target to propose when the Deploy dialog opens.
// Prefers Standalone Agent when the user is currently on an Agent diagram —
// otherwise falls back to the first available target (Web App by default).
// Caller must ensure availableTargets is non-empty.
const preferredDeployTarget = (
  project: BesserProject | null,
  availableTargets: DeploymentTarget[],
): DeploymentTarget => {
  if (project?.currentDiagramType === 'AgentDiagram' && availableTargets.includes('agent')) {
    return 'agent';
  }
  return availableTargets[0];
};

interface UseDeploymentOptions {
  currentProject: BesserProject | null;
  isDeploymentAvailable: boolean;
}

export function useDeployment({ currentProject, isDeploymentAvailable }: UseDeploymentOptions) {
  const {
    isAuthenticated,
    githubSession,
  } = useGitHubAuth();
  const { deployToRender, isDeploying: isDeployingToRender, deploymentResult } = useRenderDeploy();

  const [isDeployDialogOpen, setIsDeployDialogOpen] = useState(false);
  const [isDeployResultOpen, setIsDeployResultOpen] = useState(false);
  const [githubRepoName, setGithubRepoName] = useState('');
  const [githubRepoDescription, setGithubRepoDescription] = useState('');
  const [githubRepoPrivate, setGithubRepoPrivate] = useState(false);
  const [useExistingRepo, setUseExistingRepo] = useState(false);
  const [linkedRepo, setLinkedRepo] = useState<{ owner: string; repo: string } | null>(null);
  const [commitMessage, setCommitMessage] = useState('');
  const [deploymentTarget, setDeploymentTarget] = useState<DeploymentTarget>('webapp');
  const [includePersonalization, setIncludePersonalization] = useState(false);

  const showPersonalizationOption = useMemo(
    () => hasPersonalizationVariants(currentProject),
    [currentProject],
  );

  // If variants disappear (diagram switched, variants cleared), drop the toggle
  // so we never send a stale mapping to the backend.
  useEffect(() => {
    if (!showPersonalizationOption && includePersonalization) {
      setIncludePersonalization(false);
    }
  }, [showPersonalizationOption, includePersonalization]);

  const availableDeployTargets = useMemo<DeploymentTarget[]>(() => {
    const targets: DeploymentTarget[] = [];
    if (hasWebAppDeploymentInputs(currentProject)) {
      targets.push('webapp');
    }
    if (hasAgentDeploymentInputs(currentProject)) {
      targets.push('agent');
    }
    return targets;
  }, [currentProject]);

  // Reset linked repo state when project/target changes.
  useEffect(() => {
    if (currentProject) {
      const linked = LocalStorageRepository.getDeployLinkedRepo(currentProject.id, deploymentTarget);
      setLinkedRepo(linked);
      setUseExistingRepo(!!linked);
    } else {
      setLinkedRepo(null);
      setUseExistingRepo(false);
    }
  }, [currentProject?.id, deploymentTarget]);

  const handleOpenDeployDialog = useCallback(() => {
    if (!isDeploymentAvailable) {
      toast.info('Deploy is available for Web App and Agent diagrams.');
      return;
    }
    if (!isAuthenticated) {
      toast.info('Connect to GitHub first.');
      return;
    }
    if (!currentProject) {
      toast.error('Create or load a project first.');
      return;
    }

    if (availableDeployTargets.length === 0) {
      toast.info('Deploy requires Class + GUI diagrams (Web App) or at least one Agent diagram (Standalone Agent).');
      return;
    }

    const initialTarget = preferredDeployTarget(currentProject, availableDeployTargets);
    setDeploymentTarget(initialTarget);

    setCommitMessage('');
    const linked = LocalStorageRepository.getDeployLinkedRepo(currentProject.id, initialTarget);
    if (linked) {
      setLinkedRepo(linked);
      setGithubRepoName(linked.repo);
      setUseExistingRepo(true);
    } else {
      setLinkedRepo(null);
      setUseExistingRepo(false);
      setGithubRepoName(defaultRepoNameForTarget(currentProject.name, initialTarget));
    }
    setGithubRepoDescription(defaultDescriptionForTarget(initialTarget));
    setGithubRepoPrivate(false);
    setIsDeployDialogOpen(true);
  }, [isDeploymentAvailable, isAuthenticated, currentProject, availableDeployTargets]);

  const handleOpenDeployDialogRef = useRef(handleOpenDeployDialog);
  handleOpenDeployDialogRef.current = handleOpenDeployDialog;

  // Listen for assistant-driven deploy event
  useEffect(() => {
    const handleAssistantDeploy = (_e: Event) => {
      handleOpenDeployDialogRef.current();
    };

    window.addEventListener('wme:assistant-deploy-app', handleAssistantDeploy);
    return () => window.removeEventListener('wme:assistant-deploy-app', handleAssistantDeploy);
  }, []);

  const handleDeploymentTargetChange = useCallback((target: DeploymentTarget) => {
    setDeploymentTarget(target);
    // Reset personalization toggle when switching targets — it only applies to
    // agent deploys, and a stale "on" from a previous agent session
    // shouldn't leak into a fresh webapp -> agent switch.
    if (target !== 'agent') {
      setIncludePersonalization(false);
    }
    if (!currentProject) {
      return;
    }

    const linked = LocalStorageRepository.getDeployLinkedRepo(currentProject.id, target);
    if (linked) {
      setLinkedRepo(linked);
      setUseExistingRepo(true);
      setGithubRepoName(linked.repo);
    } else {
      setLinkedRepo(null);
      setUseExistingRepo(false);
      setGithubRepoName(defaultRepoNameForTarget(currentProject.name, target));
    }
    setGithubRepoDescription(defaultDescriptionForTarget(target));
    setCommitMessage('');
  }, [currentProject]);

  const handlePublishToRender = useCallback(async () => {
    if (!currentProject) {
      toast.error('No project available for deployment.');
      return;
    }
    if (!githubSession) {
      toast.error('GitHub session not found. Please reconnect.');
      return;
    }
    if (!githubRepoName.trim()) {
      toast.error('Repository name is required.');
      return;
    }

    const projectForDeploy = ProjectStorageRepository.loadProject(currentProject.id) || currentProject;

    let personalizationMapping: PersonalizationMappingEntry[] | null = null;
    if (deploymentTarget === 'agent' && includePersonalization) {
      const mapping = buildPersonalizationMapping(projectForDeploy);
      if (mapping.length === 0) {
        toast.error('No valid personalization mappings found. Save personalized variants before enabling this option.');
        return;
      }
      personalizationMapping = mapping;
    }

    // Webapp deploys embed the agent model directly in the generated app, so
    // always ship the base (pre-personalization) snapshot — and a system-only
    // agent config — even if the user ran Save & Apply in the Agent
    // Configuration panel. This matches the "None" selection in the
    // standalone agent generator.
    const projectForPayload: BesserProject = deploymentTarget === 'webapp'
      ? stripAgentConfigToSystem(restoreBaseAgentModels(projectForDeploy))
      : projectForDeploy;

    const result = await deployToRender(projectForPayload, {
      repoName: sanitizeRepoName(githubRepoName),
      description: githubRepoDescription.trim() || defaultDescriptionForTarget(deploymentTarget),
      isPrivate: githubRepoPrivate,
      githubSession,
      useExisting: useExistingRepo,
      commitMessage,
      deploymentTarget,
      personalizationMapping,
    });

    if (result?.success) {
      LocalStorageRepository.setDeployLinkedRepo(currentProject.id, deploymentTarget, {
        owner: result.owner,
        repo: result.repo_name,
      });
      setIsDeployDialogOpen(false);
      setIsDeployResultOpen(true);

      getPostHog()?.capture('render_deploy_success', {
        deployment_status: 'success',
        is_private: githubRepoPrivate,
        repo_name: githubRepoName,
        repo_url: result.repo_url,
        owner: result.owner,
        files_uploaded: result.files_uploaded,
        is_redeployment: useExistingRepo,
        diagram_type: currentProject.currentDiagramType,
        deployment_target: deploymentTarget,
      });
    } else {
      getPostHog()?.capture('render_deploy_failure', {
        deployment_status: 'failed',
        is_private: githubRepoPrivate,
        repo_name: githubRepoName,
        diagram_type: currentProject.currentDiagramType,
        deployment_target: deploymentTarget,
      });
    }
  }, [currentProject, githubSession, githubRepoName, githubRepoDescription, githubRepoPrivate, useExistingRepo, commitMessage, deployToRender, deploymentTarget, includePersonalization]);

  const handleCreateNewInstead = useCallback(() => {
    if (currentProject?.id) {
      LocalStorageRepository.clearDeployLinkedRepo(currentProject.id, deploymentTarget);
    }
    setLinkedRepo(null);
    setUseExistingRepo(false);
    setGithubRepoName(defaultRepoNameForTarget(currentProject?.name || '', deploymentTarget));
  }, [currentProject, deploymentTarget]);

  return {
    // State
    isDeployDialogOpen,
    isDeployResultOpen,
    githubRepoName,
    githubRepoDescription,
    githubRepoPrivate,
    useExistingRepo,
    linkedRepo,
    commitMessage,
    deploymentTarget,
    availableDeployTargets,
    isDeployingToRender,
    deploymentResult,
    includePersonalization,
    showPersonalizationOption,

    // Setters
    setIsDeployDialogOpen,
    setIsDeployResultOpen,
    setGithubRepoName,
    setGithubRepoDescription,
    setGithubRepoPrivate,
    setCommitMessage,
    setIncludePersonalization,

    // Handlers
    handleOpenDeployDialog,
    handleDeploymentTargetChange,
    handlePublishToRender,
    handleCreateNewInstead,
  };
}
