import React, { useState } from 'react';
import { Dropdown, NavDropdown, Modal, Form, Button, Alert } from 'react-bootstrap';
import { useGitHubAuth } from '../../../services/github/useGitHubAuth';
import { useDeployToGitHub } from '../../../services/deploy/useGitHubDeploy';
import { useAppSelector } from '../../store/hooks';
import { toast } from 'react-toastify';
import { UMLDiagramType } from '@besser/wme';
import { ProjectStorageRepository } from '../../../services/storage/ProjectStorageRepository';
import posthog from 'posthog-js';

export const DeployMenu: React.FC = () => {
  // Render deployment state
  const [showRenderModal, setShowRenderModal] = useState(false);
  const [githubRepoName, setGithubRepoName] = useState('');
  const [githubRepoDescription, setGithubRepoDescription] = useState('');
  const [githubRepoPrivate, setGithubRepoPrivate] = useState(false);
  const [showDeploymentLinks, setShowDeploymentLinks] = useState(false);

  const { isAuthenticated, username, githubSession } = useGitHubAuth();
  const { deployToGitHub, isDeploying: isDeployingToRender, deploymentResult } = useDeployToGitHub();
  const diagram = useAppSelector((state) => state.diagram.diagram);
  const currentDiagramType = useAppSelector((state) => state.diagram.editorOptions.type);

  // Detect if we're on the Quantum Circuit editor page
  const isQuantumDiagram = /quantum-editor/.test(typeof window !== 'undefined' ? window.location.pathname : '');
  // Detect if we're on the GraphicalUIEditor GUI / No-Code editor page
  const isGUINoCodeDiagram = /graphical-ui-editor/.test(typeof window !== 'undefined' ? window.location.pathname : '');

  // Helper to get model size metrics for analytics
  const getModelMetrics = () => {
    if (!diagram?.model) return { elements_count: 0, classes_count: 0, relationships_count: 0, total_size: 0 };
    const model = diagram.model as any;
    
    const allElementsCount = model.elements ? Object.keys(model.elements).length : 0;
    const classesCount = model.elements 
      ? Object.values(model.elements).filter((el: any) => el.type === 'Class').length 
      : 0;
    
    const relationshipsCount = model.relationships ? Object.keys(model.relationships).length : 0;
    
    return { 
      elements_count: allElementsCount,
      classes_count: classesCount,
      relationships_count: relationshipsCount,
      total_size: allElementsCount + relationshipsCount
    };
  };

  // Check if deployment is available for current diagram type
  const isClassDiagram = currentDiagramType === UMLDiagramType.ClassDiagram;
  const isDeploymentAvailable = isGUINoCodeDiagram || isClassDiagram;

  const handleRenderDeploy = async () => {
    if (!githubRepoName.trim()) {
      toast.error('Please enter a repository name');
      return;
    }

    if (!githubSession) {
      toast.error('GitHub session not found');
      return;
    }

    const currentProject = ProjectStorageRepository.getCurrentProject();
    if (!currentProject) {
      toast.error('No project available for deployment');
      return;
    }

    const result = await deployToGitHub(
      currentProject,
      githubRepoName,
      githubRepoDescription || 'Web application generated by BESSER',
      githubRepoPrivate,
      githubSession
    );

    if (result) {
      setShowRenderModal(false);
      setShowDeploymentLinks(true);
      posthog.capture('render_deploy_success', {
        deployment_status: 'success',
        is_private: githubRepoPrivate,
        repo_name: githubRepoName,
        repo_url: result.repo_url,
        owner: result.owner,
        files_uploaded: result.files_uploaded,
        diagram_type: currentDiagramType,
        ...getModelMetrics()
      });
    } else {
      posthog.capture('render_deploy_failure', {
        deployment_status: 'failed',
        is_private: githubRepoPrivate,
        repo_name: githubRepoName,
        diagram_type: currentDiagramType,
        ...getModelMetrics()
      });
    }
  };

  const handleInitiateRenderDeploy = () => {
    if (!isAuthenticated) {
      toast.info('Please connect to GitHub first using the button in the top bar');
    } else {
      // Already signed in, show deploy modal
      setShowRenderModal(true);
      // Set default repo name from project name
      const currentProject = ProjectStorageRepository.getCurrentProject();
      if (currentProject) {
        const defaultName = currentProject.name.toLowerCase().replace(/\s+/g, '-');
        setGithubRepoName(defaultName);
      }
    }
  };

  // Don't render the menu if deployment is not available
  if (!isDeploymentAvailable) {
    return null;
  }

  return (
    <>
      <NavDropdown title="Deploy" className="pt-0 pb-0">
        <Dropdown.Item 
          onClick={handleInitiateRenderDeploy}
          disabled={!isAuthenticated}
          title="Creates a GitHub repo with your web app code, then deploys it to Render with one click"
        >
          {isAuthenticated ? `Publish Web App to Render` : 'Publish Web App to Render (Connect GitHub first)'}
        </Dropdown.Item>
      </NavDropdown>

      {/* Publish to Render Modal */}
      <Modal show={showRenderModal} onHide={() => setShowRenderModal(false)} size="lg">
        <Modal.Header closeButton>
          <Modal.Title>Publish to Render</Modal.Title>
        </Modal.Header>
        <Modal.Body>
          <Alert variant="info">
            <strong>How it works:</strong>
            <ol className="mb-0 mt-2">
              <li>We'll create a repository in your GitHub account</li>
              <li>Push your web app code to that repository</li>
              <li>Deploy to Render with one click!</li>
            </ol>
          </Alert>

          <Form>
            <Form.Group className="mb-3">
              <Form.Label>Repository Name</Form.Label>
              <Form.Control
                type="text"
                placeholder="my-awesome-app"
                value={githubRepoName}
                onChange={(e) => setGithubRepoName(e.target.value)}
              />
              <Form.Text className="text-muted">
                Lowercase, hyphens and underscores only
              </Form.Text>
            </Form.Group>

            <Form.Group className="mb-3">
              <Form.Label>Description (optional)</Form.Label>
              <Form.Control
                type="text"
                placeholder="Web application generated by BESSER"
                value={githubRepoDescription}
                onChange={(e) => setGithubRepoDescription(e.target.value)}
              />
            </Form.Group>

            <Form.Group className="mb-3">
              <Form.Check
                type="checkbox"
                label="Make repository private"
                checked={githubRepoPrivate}
                onChange={(e) => setGithubRepoPrivate(e.target.checked)}
              />
              {githubRepoPrivate && (
                <Alert variant="warning" className="mt-2 mb-0">
                  <small>
                    <strong>⚠️ Private Repository:</strong> The one-click "Deploy to Render" button won't work. 
                    You'll need to manually connect your GitHub account to Render and grant access to private repositories.
                  </small>
                </Alert>
              )}
            </Form.Group>
          </Form>
        </Modal.Body>
        <Modal.Footer>
          <Button variant="secondary" onClick={() => setShowRenderModal(false)}>
            Cancel
          </Button>
          <Button
            variant="primary"
            onClick={handleRenderDeploy}
            disabled={isDeployingToRender || !githubRepoName.trim()}
          >
            {isDeployingToRender ? 'Publishing...' : 'Publish to Render'}
          </Button>
        </Modal.Footer>
      </Modal>

      {/* Deployment Links Modal */}
      <Modal show={showDeploymentLinks} onHide={() => setShowDeploymentLinks(false)} size="lg">
        <Modal.Header closeButton>
          <Modal.Title>🎉 Repository Created Successfully!</Modal.Title>
        </Modal.Header>
        <Modal.Body>
          {deploymentResult && (
            <>
              <Alert variant="success">
                <strong>Repository:</strong>{' '}
                <a href={deploymentResult.repo_url} target="_blank" rel="noopener noreferrer">
                  {deploymentResult.owner}/{deploymentResult.repo_name}
                </a>
                <br />
                <small>{deploymentResult.files_uploaded} files uploaded</small>
              </Alert>

              <h5 className="mt-4 mb-3">🚀 Deploy Your App:</h5>

              <div className="d-grid gap-3">
                <a
                  href={deploymentResult.deployment_urls.render}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="btn btn-success btn-lg"
                >
                  <strong>Deploy to Render</strong>
                  <br />
                  <small className="text-white-50">Free full-stack deployment (Frontend + Backend)</small>
                </a>

                <a
                  href={deploymentResult.repo_url}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="btn btn-outline-secondary"
                >
                  View on GitHub
                </a>
              </div>

              <Alert variant="info" className="mt-4">
                <small>
                  <strong className="d-block mt-2">Next step:</strong> Click "Deploy to Render" above, sign in (free), and your app will be live in ~2 minutes!
                </small>
              </Alert>
            </>
          )}
        </Modal.Body>
        <Modal.Footer>
          <Button variant="primary" onClick={() => setShowDeploymentLinks(false)}>
            Done
          </Button>
        </Modal.Footer>
      </Modal>
    </>
  );
};
